openapi: 3.0.0
info:
  title: An example OpenAPI document
  description: |
    This API allows writing down marks on a Tic Tac Toe board
    and requesting the state of the board or of individual squares.
  version: 0.0.1
paths: {} # No endpoints defined yet
